{
    "name": "trn Student",
    "version": "19.0.1.2.0",
    "category": "trn/Education",
    "summary": "Student records, per-semester admission, subject offerings and grades",
    "author": "Your Organization",
    "website": "",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": [],
    "depends": ["base", "trn_security"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/department_views.xml",
        "views/subject_views.xml",
        "views/faculty_views.xml",
        "views/subject_offering_views.xml",
        "views/student_views.xml",
        "views/course_views.xml",
        "views/menus.xml",
    ],
    "demo": [
        "demo/student_demo.xml",
        "demo/subject_demo.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
