{
    "name": "trn Service Request",
    "version": "19.0.1.0.0",
    "category": "trn/Operations",
    "summary": "IT service request ticketing across offices",
    "author": "Your Organization",
    "website": "",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": [],
    "depends": ["mail", "trn_office", "trn_vocabulary"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/ir_sequence.xml",
        "data/service_vocabulary.xml",
        "data/service_catalog_data.xml",
        "data/mail_template.xml",
        "views/service_request_views.xml",
        "views/service_catalog_views.xml",
        "views/service_team_views.xml",
        "wizard/service_request_rating_wizard_views.xml",
        "views/menus.xml",
    ],
    "demo": [
        "demo/service_request_demo.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
