from . import test_course
from . import test_department
from . import test_subject
from . import test_faculty
from . import test_subject_offering
from . import test_grade
from . import test_student
from . import test_security
from . import test_demo_data
